name: Proot Build
on: 
  workflow_dispatch:

jobs:
  build-proot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Set up Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r28c
    
    - name: Set up Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make tar gzip dos2unix

    - name: Build Proot
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        cd proot
        ./build.sh
    
    - name: Upload PRoot artifacts
      uses: actions/upload-artifact@v4
      with:
        name: proot-binaries
        path: ./proot/packages

  build-termux-exec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, arm, x86_64, i686]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build termux-exec
      run: |
        mkdir -p ./out
        docker run --rm --privileged \
          -v ${{ github.workspace }}:/workspace \
          termux/termux-docker:${{ matrix.arch }} \
          bash -c "
            apt update && pkg install -y clang git make termux-create-package wget
            /workspace/termux-exec-build.sh
          "
        ls ./out
        
    - name: Upload termux-exec artifacts
      uses: actions/upload-artifact@v4
      with:
        name: termux-exec-${{ matrix.arch }}
        path: ./out